# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - next

jobs:
  main:
    uses: the-nexim/actions/.github/workflows/build-lint-test.yaml@v1
    with:
      node-version: 22.11.0
    secrets: inherit
