# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Dependency Review

on:
  workflow_dispatch:

  pull_request:

jobs:
  main:
    uses: the-nexim/actions/.github/workflows/dependency-review.yaml@v1
    permissions:
      contents: read
