# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Lint & Test & Release

on:
  workflow_dispatch:

env:
  NODE_VERSION: lts/*
  GPG_KEY_ID: ${{ vars.GPG_KEY_ID }}

jobs:
  main:
    uses: the-nexim/actions/.github/workflows/release.yaml@v1
    permissions:
      contents: read
    with:
      NODE_VERSION: lts/*
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
