# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Sync labels

on:
  workflow_dispatch:
  push:
    branches:
      - next
    paths:
      - .github/labels.yml

jobs:
  main:
    uses: the-nexim/actions/.github/workflows/sync-labels.yml@v1
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
